### ISSUE TITLE
New testing utility

### ISSUE THREAD

**Issue by heitorlessa** [aws-powertools/powertools-lambda-python#1169]
> Original author: @beanaroo

**Runtime:** Python

**Is your feature request related to a problem? Please describe**

As per this [discussion](https://github.com/awslabs/aws-lambda-powertools-python/discussions/337), creating test events for Lambda event sources is a laborious process.

Finding the correct event with default values tend to be **1/** invoking a Lambda function, **2/** logging the event, **3/** extracting the log event from CloudWatch, **4/** serializing back to native Python object, **5/** creating a Pytest fixture that can be used across tests.

> NOTE: When the event source is supported by SAM CLI, this cycle can be shortened with `sam local generate-event` sub-command

This cycle repeats when you're trying to mock Lambda Context for libraries and middlewares that make use of it.

**Describe the solution you'd like**

Make [tests events available](https://github.com/awslabs/aws-lambda-powertools-python/tree/develop/tests/events) in the project as Dataclasses that can be initialized with default values and changed as we see please.

```python
from aws_lambda_powertools.utilities.testing import LambdaContext, ApiGatewayProxyEvent

import app

def test_handler():
    app.handler(event=ApiGatewayProxyEvent(), context=LambdaContext())
```

**Describe alternatives you've considered**

Create my own default Lambda Context using LambdaContext typing

```python
import pytest
from aws_lambda_powertools.utilities.typing import LambdaContext


class MockLambdaContext(LambdaContext):

    def __init__(self):
        self._function_name = 'test-fn'
        self._memory_limit_in_mb = 128
        self._invoked_function_arn = 'arn:aws:lambda:us-east-1:12345678:function:test-fn'
        self._aws_request_id = '52fdfc07-2182-154f-163f-5f0f9a621d72'


@pytest.fixture
def lambda_context() -> LambdaContext:
    return MockLambdaContext()


def test_handler(lambda_context):
    app.handler(event={}, context=lambda_context)
```

**If you provide guidance, is this something you'd like to contribute?**

**Additional context**

**Comment by heitorlessa** [comment]
Hey Noah, could you give an example of the experience you’re after?

Tracer automatically disabled I/O during unit testing, so no changes
needed. Logger needs a fake Lambda context (we have on our docs). Metrics
only needs a fake Lambda context when capturing cold start.

While we document how to test each feature, I’m super keen to hear how we
can make that easier.

Thank you ;-)

**Comment by walmsles** [comment]
This is needed and very useful.  Almost need a separate project that harvests Lambda events from real AWS infrastructure and uses these "events" to generate data classes - this sounds so simple as I type it 😬.  

Also need to split out much of the test components within the main repo - it is reusable.  Would save people from taking parts and adapting them to their needs (like I have done [here](https://github.com/walmsles/aws-lambda-python-cdk)).

**Comment by heitorlessa** [comment]
We're closing feature requests older than a year that haven't received enough customers +1 or that we were unable to prioritize. For newer customers interested in, please feel free to comment and we can reopen it.

On Testing, this is something we won't be able to do this year. If a newer customer sees this in 2024, please feel free to comment and we can revisit it
