### ISSUE TITLE
Add in RE_* support as feature_flag action

### ISSUE THREAD

**Issue by whardier** [aws-powertools/powertools-lambda-python#1178]
**Is your feature request related to a problem? Please describe.**

Just a feature request

**Describe the solution you'd like**

Add in extra actions to test for regular expression matches/searches.

**Describe alternatives you've considered**

I actually think in many cases the current actions are sufficient.  There are always cases where using a regular expression fills the gap and I've already found one where I need to test legacy data to enable a toggle by way of a re.search.

**Additional context**

See linked PR awslabs/aws-lambda-powertools-python#692

**Comment by heitorlessa** [comment]
We're closing feature requests older than a year that haven't received enough customers +1 or that we were unable to prioritize. For newer customers interested in, please feel free to comment and we can reopen it.
