### ISSUE TITLE
Maintenance: Break down event_source_data_classes tests

### ISSUE THREAD

**Issue by heitorlessa** [aws-powertools/powertools-lambda-python#509]
Issue: #504

Functional tests for event source data classes utility are now 1.3K LOC in a single file. This issue tracks resolving them into a test per event source to ease maintenance and contrib

**Comment by michaelbrewer** [comment]
@heitorlessa - i don't mind splitting this up :)

**Comment by heitorlessa** [comment]
I don’t mind at all the extra hand helping out ;-)

**Comment by michaelbrewer** [comment]
@heitorlessa - do you think this is still necessary? These tests are extremely fast, so it is not for performance reasons. Going forward for new types of event sources, i will make sure to split out the tests. And if there is any major refactoring or changes to the existing ones.
