### ISSUE TITLE
Maintenance: Create API and infrastructure for docs anonymous page views

### ISSUE THREAD

**Issue by heitorlessa** [aws-powertools/powertools-lambda-python#510]
As of now, docs use Amplify Analytics module to send anonymous page views to Kinesis Firehose async. This means Amplify JS has to be loaded for it to work and might degrade customers experience in low bandwidth scenarios.

This issue tracks the resolution of creating an API for tracking page views anonymously, and all related infrastructure that should be thought out.

**Comment by DanyC97** [comment]
Being curious (as is a new area for me hence keen to learn), once you have the data what sort of metrics are you looking into it apart from a count of how many unique users are viewing the pages? And are the metrics used to drive insights into something useful for the project?

**Comment by michaelbrewer** [comment]
@DanyC97 - i think it helps see which specific utilities people are interested in.
